<?php

namespace AppBundle\Repository;

/**
 * IdiomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdiomRepository extends \Doctrine\ORM\EntityRepository
{
}
