<?php

namespace AppBundle\Repository;

/**
 * MiniGlossaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MiniGlossaryRepository extends \Doctrine\ORM\EntityRepository
{
}
