idiom_index:
    path:     /
    defaults: { _controller: "AppBundle:Idiom:index" }
    methods:  GET

idiom_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Idiom:show" }
    methods:  GET

idiom_new:
    path:     /new
    defaults: { _controller: "AppBundle:Idiom:new" }
    methods:  [GET, POST]

idiom_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Idiom:edit" }
    methods:  [GET, POST]

idiom_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Idiom:delete" }
    methods:  DELETE
