miniglossary_index:
    path:     /
    defaults: { _controller: "AppBundle:MiniGlossary:index" }
    methods:  GET

miniglossary_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:MiniGlossary:show" }
    methods:  GET

miniglossary_new:
    path:     /new
    defaults: { _controller: "AppBundle:MiniGlossary:new" }
    methods:  [GET, POST]

miniglossary_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:MiniGlossary:edit" }
    methods:  [GET, POST]

miniglossary_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:MiniGlossary:delete" }
    methods:  DELETE

miniglossary_search:
    path:     /search
    defaults: { _controller: "AppBundle:MiniGlossary:search" }
    methods:  [GET, POST]
