term_index:
    path:     /
    defaults: { _controller: "AppBundle:Term:index" }
    methods:  GET

term_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Term:show" }
    methods:  GET

term_new:
    path:     /new
    defaults: { _controller: "AppBundle:Term:new" }
    methods:  [GET, POST]

term_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Term:edit" }
    methods:  [GET, POST]

term_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Term:delete" }
    methods:  DELETE
