app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix:   /user

app_miniglossary:
        resource: "@AppBundle/Resources/config/routing/miniglossary.yml"
        prefix:   /glossary
app_term:
    resource: "@AppBundle/Resources/config/routing/term.yml"
    prefix:   /term

app_translate:
    resource: "@AppBundle/Resources/config/routing/translate.yml"
    prefix:   /translate

app_idiom:
    resource: "@AppBundle/Resources/config/routing/idiom.yml"
    prefix:   /idiom

app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix:   /user

login:
    path:     /login
    defaults: { _controller: "AppBundle:User:login" }
    methods:  [GET,POST]

user_registration:
    path:     /register
    defaults: { _controller: "AppBundle:User:register" }
    methods:  [GET,POST]

logout:
    path:     /logout
    defaults: { _controller: "AppBundle:User:logout" }
    methods:  [GET,POST]
